name: QT6 CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt6
        uses: jurplel/install-qt-action@v4.3.0
        with:
          version: 6.9.1
          host: windows
          target: desktop
          arch: win64_mingw
          modules: qtmultimedia
          tools: tools_mingw qt.tools.win64_mingw1310

      - name: Configure and Build
        run: |
          cd D:\a\SlayTheShrike\Qt
          ls
          cd .\Tools
          ls
          # mkdir build
          # cd build
          # cmake -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="${{ env.QT_INSTALL_DIR }}/6.9.1/mingw_64" -DCMAKE_CXX_COMPILER="${{ env.QT_INSTALL_DIR }}/6.9.1/mingw_64/bin/g++.exe" ..
          # cmake --build . -j
